### ISSUE TITLE
possible_words is not defined (Typer.js)

### ISSUE THREAD

**Issue by thanhgaming5550** [corropted/dj-games#5]
**Describe the bug**
`possible_words` is not defined (Typer.js)

**Node log :** 

```
2021-07-22T04:21:03.374245+00:00 app[worker.1]: Thu Jul 22 2021 04:21:03 GMT+0000 (Coordinated Universal Time) | thanhgaming5550#5550 <@384282911479693313> : />typer
2021-07-22T04:21:03.377775+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: ReferenceError: possible_words is not defined
2021-07-22T04:21:03.377779+00:00 app[worker.1]:     at typer.startGame (/app/node_modules/dj-games/games/Typer.js:12:53)
2021-07-22T04:21:03.377780+00:00 app[worker.1]:     at Object.run (/app/commands/typer.js:10:15)
2021-07-22T04:21:03.377780+00:00 app[worker.1]:     at Client.<anonymous> (/app/index.js:68:42)
2021-07-22T04:21:03.377781+00:00 app[worker.1]:     at Client.emit (events.js:375:28)
2021-07-22T04:21:03.377792+00:00 app[worker.1]:     at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
2021-07-22T04:21:03.377793+00:00 app[worker.1]:     at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
2021-07-22T04:21:03.377795+00:00 app[worker.1]:     at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
2021-07-22T04:21:03.377796+00:00 app[worker.1]:     at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
2021-07-22T04:21:03.377796+00:00 app[worker.1]:     at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
2021-07-22T04:21:03.377796+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
2021-07-22T04:21:03.377797+00:00 app[worker.1]:     at WebSocket.emit (events.js:375:28)
2021-07-22T04:21:03.377797+00:00 app[worker.1]:     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:834:20)
2021-07-22T04:21:03.377797+00:00 app[worker.1]:     at Receiver.emit (events.js:375:28)
2021-07-22T04:21:03.377798+00:00 app[worker.1]:     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:437:14)
2021-07-22T04:21:03.377798+00:00 app[worker.1]:     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:367:17)
2021-07-22T04:21:03.377798+00:00 app[worker.1]:     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:143:22)
2021-07-22T04:21:03.377799+00:00 app[worker.1]: (Use `node --trace-warnings ...` to show where the warning was created)
2021-07-22T04:21:03.388294+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2021-07-22T04:21:03.388370+00:00 app[worker.1]: (node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**My Code :**
```js
const games = require('dj-games')
const typer = new games.typer()

module.exports = {
    name: "typer",
    description: "solo go 10 ngon",

    async run(client, message, args) {
        console.log(`${message.createdAt} | ${message.author.tag} ${message.author} : ${message}`)
        typer.startGame(message)
    }
}

```
_(i use commands handler)_

**Version :**
```json
"discord.js": "^12.5.3"
"dj-games": "^3.0.0"

"node" : "v14.17.0"
"npm" : "6.14.13"

```

**Comment by corropted** [comment]
Oh

**Comment by corropted** [comment]
sry about it i fixed it use ommand  npm i dj-games@latest
